import express from "express";
import Community from "../models/community.model.js";
import User from "../models/user.model.js";
import Message from "../models/message.model.js";
import { protectRoute } from '../middleware/protectRoute.js';
import { getAllCommunities, getCommunityById, joinCommunity, leaveCommunity, deleteCommunity } from "../controllers/community.controllers.js";
import axios from 'axios';
import { ENV_CONFIG } from "../config/environment.js";

const router = express.Router();

// 1. Create a community
router.post('/', protectRoute, async (req, res) => {
  try {
    const { name, description, image, userId } = req.body;

    // Get public and private keys generated by Flask
    const { data: keys } = await axios.post(`${ENV_CONFIG.PQCLEAN_API_URL}/generate_keys`, {
      kem_name: "ML-KEM-512",
    });

    const dsaResponse = await axios.post(`${ENV_CONFIG.PQCLEAN_API_URL}/generate_ml_dsa_keys`, {
      ml_dsa_variant: "ML-DSA-44",
    });

    const { public_key: public_key2, private_key: private_key2 } = dsaResponse.data;

    const newCommunity = new Community({
      name,
      description,
      image,
      members: [userId],
      admins: [userId],
      publicKey: keys.public_key,
      privateKey: keys.secret_key,
      publicKeyDSA: public_key2,
      privateKeyDSA: private_key2,
    });

    const savedCommunity = await newCommunity.save();
    res.status(201).json(savedCommunity);
  } catch (error) {
    console.error("Error creating community:", error);
    res.status(500).json({ message: 'Error creating community', error });
  }
});

// 2. Get all communities
router.get('/', protectRoute, getAllCommunities);

// 3. Get a community by ID
router.get('/:id', protectRoute, getCommunityById);



// 4. Get community messages, decrypt them, and verify them
const axiosRetry = async (url, data, retries = 3) => {
  for (let i = 0; i < retries; i++) {
    try {
      return await axios.post(url, data);
    } catch (error) {
      if (i === retries - 1) throw error;
      await new Promise(r => setTimeout(r, 1000));
    }
  }
};

const bulkDecryptResponse = (data) => axiosRetry(`${ENV_CONFIG.PQCLEAN_API_URL}/bulkDecrypt`, data);
const bulkVerifyResponse = (data) => axiosRetry(`${ENV_CONFIG.PQCLEAN_API_URL}/bulkVerify`, data);

router.get('/:id/messages', protectRoute, async (req, res) => {
  const { id: communityId } = req.params;

  try {
    // Get the community with its messages
    const community = await Community.findById(communityId).populate('messages');

    if (!community) {
      return res.status(404).json({ error: 'Community not found' });
    }

    // Check if community has messages
    if (!community.messages || community.messages.length === 0) {
      return res.status(200).json([]);
    }

    // Verify that the community has its private key
    const secretKeyBase64 = community.privateKey;
    if (!secretKeyBase64) {
      return res.status(400).json({ error: "Community does not have a private key." });
    }

    // Process all messages in the community
    const messages = community.messages;

    // Check if messages have required fields
    const validMessages = messages.filter(msg => msg.message && msg.sharedSecret);

    if (validMessages.length === 0) {
      return res.status(200).json([]);
    }

    try {
      // 1. Prepare bulkDecrypt
      const bulkDecryptInput = validMessages.map(msg => ({
        ciphertext: msg.message,
        shared_secret: msg.sharedSecret
      }));

      const bulkDecryptResult = await bulkDecryptResponse({
        kem_name: "ML-KEM-512",
        messages: bulkDecryptInput
      });

      const decryptedMessagesArray = bulkDecryptResult.data.results;

      // 2. Prepare bulkVerify
      const bulkVerifyInput = decryptedMessagesArray.map((decrypted, index) => ({
        message: decrypted.original_message,
        signature: validMessages[index].signature,
        public_key: validMessages[index].publicKeyDSA,
        ml_dsa_variant: "ML-DSA-44"
      }));

      const bulkVerifyResult = await bulkVerifyResponse({
        messages: bulkVerifyInput
      });

      const verificationResults = bulkVerifyResult.data.results;

      // 3. Combine decrypted + verified
      const formattedMessages = validMessages.map((msg, index) => ({
        _id: msg._id,
        message: decryptedMessagesArray[index].original_message,
        senderId: msg.senderId,
        receiverId: msg.receiverId,
        signature: msg.signature,
        publicKeyDSA: msg.publicKeyDSA,
        sharedSecret: msg.sharedSecret,
        fileUrl: msg.fileUrl || null,
        fileName: msg.fileName || null,
        fileSize: msg.fileSize || null,
        verified: verificationResults[index].verified,
        createdAt: msg.createdAt,
        updatedAt: msg.updatedAt
      }));

      res.status(200).json(formattedMessages);
    } catch (decryptError) {
      // Fallback: return encrypted messages if decryption fails
      const fallbackMessages = messages.map(msg => ({
        _id: msg._id,
        message: msg.message,
        senderId: msg.senderId,
        receiverId: msg.receiverId,
        signature: msg.signature,
        publicKeyDSA: msg.publicKeyDSA,
        sharedSecret: msg.sharedSecret,
        fileUrl: msg.fileUrl || null,
        fileName: msg.fileName || null,
        fileSize: msg.fileSize || null,
        verified: false,
        createdAt: msg.createdAt,
        updatedAt: msg.updatedAt
      }));

      res.status(200).json(fallbackMessages);
    }
  } catch (error) {
    res.status(500).json({ error: "Internal server error" });
  }
});

// 5. Join a community
router.post('/:id/join', protectRoute, joinCommunity);

// 6. Send a message to a community
router.post('/:id/messages', protectRoute, async (req, res) => {
  const { id: communityId } = req.params;
  const { message, senderId, receiverId, signature, publicKeyDSA, sharedSecret, fileUrl, fileName, fileSize } = req.body;

  try {
    const newMessage = new Message({
      senderId,
      receiverId,
      signature,
      publicKeyDSA,
      message,
      sharedSecret,
      fileUrl,
      fileName,
      fileSize
    });

    const savedMessage = await newMessage.save();

    // Add the message to the community
    await Community.findByIdAndUpdate(
      communityId,
      { $push: { messages: savedMessage._id } }
    );

    res.status(201).json(savedMessage);
  } catch (error) {
    res.status(500).json({ error: "Internal server error" });
  }
});

// 7. Leave a community
router.post('/:id/leave', protectRoute, leaveCommunity);

// 8. Delete a community
router.delete('/:id', protectRoute, deleteCommunity);

export default router;